# Config file for automatic testing at travis-ci.org
language: java

jdk:
  - oraclejdk8

cache:
  directories:
  - $HOME/.m2

services:
  - docker

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
   - mvn clean verify -B

after_script:
  - cp target/site/jacoco/jacoco.xml src/main/java/jacoco.xml
  - cd src/main/java/
  - ../../../cc-test-reporter after-build -t jacoco --exit-code $TRAVIS_TEST_RESULT

after_success:
  - mvn clean package docker:build &&
    docker login -u="$QUAY_USERNAME" -p="$QUAY_PASSWORD" quay.io &&
    docker push quay.io/amertkara/user-data-manager
